name: security-buddy
run-name: '[security-buddy][${{ github.workflow }}] - ${{ github.event.issue.title }}'
on:
  pull_request:
    types: ['opened']
  issue_comment:
    types: ['created']
jobs:
  security-buddy:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: DryRunSec/security_buddy@v1
        with:
          openai-key: ${{ secrets.OPENAI_KEY }}
          user-whitelist: ${{ vars.CHAT_IN_ISSUE_USER_WHITELIST }}
